### ISSUE TITLE
Add teleop tutorial in wiki

### ISSUE THREAD

**Issue by etsardou** [stdr-simulator-ros-pkg/stdr_simulator#134]

**Comment by etsardou** [comment]
http://wiki.ros.org/stdr_simulator/Tutorials/Using%20turtlebot%20for%20teleoperation

**Comment by trainman419** [comment]
I like [teleop_twist_keyboard](http://wiki.ros.org/teleop_twist_keyboard) for my teleop, but I may be a bit biased because I'm currently the maintainer.

Also, instructing users to copy and edit installed files as root is VERY bad practice. They should be able to copy the launch file to their home directory or a pckage and run it there instead.

**Comment by etsardou** [comment]
Thanx for the feedback! I changed the tutorial, in the way you proposed. Finally, it would be excellent to provide a tutorial for teleop_twist_keyboard as well, placed in 4.3 here : http://wiki.ros.org/stdr_simulator/Tutorials

**Comment by trainman419** [comment]
Tutorial created: http://wiki.ros.org/stdr_simulator/Tutorials/Teleop%20with%20teleop_twist_keyboard

**Comment by etsardou** [comment]
Thank you ;)
