### ISSUE TITLE
Include sensors in collision checking

### ISSUE THREAD

**Issue by athallas** [stdr-simulator-ros-pkg/stdr_simulator#147]
Sensors outside robot's body cross obstacles

**Comment by trainman419** [comment]
Perhaps the solution to this is to disallow placing sensors outside the body of the robot?

**Comment by etsardou** [comment]
I think I agree with you.. Some of my thoughts:

I definitely think that the user should put the sensors inside the robot's body. Now if he doesn't:
- We could do nothing, just provide a collision check of the footprint
- We could actually perform collision check for the footprint and the sensors. Though the sensors are points. What happens between the sensors point and the footprint?
- We could forbid the user to create a robot with the sensors out of the footprint. Though this requires that we must have two concurrent checks: 1) that the footprint is forming a 2D polygon (no crossing sides) and 2) that the sensors are in the aforementioned footprint.
- We could alter the footprint ourselves in order to include the sensors in it. This a) may not be good because we change the user's input without his consent and b) could be difficult in some cases due to the complexity of the footprint.

I believe the third option is more robust. Share your thoughts please..

**Comment by trainman419** [comment]
I like the third option as well.

Ignoring the sensors altogether seems like a good alternative.

I agreed that trying to change the footprint is counter to the user's input, and checking the sensor separately seems like a good way to get stuck in strange situations.

**Comment by etsardou** [comment]
Closing this. The user must provide the correct footprint so that collision is computed for all sensors.
