### ISSUE TITLE
Map showing up as either all occupied or unoccupied

### ISSUE THREAD

**Issue by RyanMJohnson** [stdr-simulator-ros-pkg/stdr_simulator#161]
Hello all,

I am experiencing some issues getting a test map to load properly.  Attached are my png map file and the contents of the corresponding yaml file.  When I load this (either with a launch file or manually via the GUI or CLI) I get a completely occupied or unoccupied map (depending on whether negate is 1 or 0).  Any ideas what could be causing this?

Thanks,
Ryan Johnson
![test](https://cloud.githubusercontent.com/assets/8484035/4077449/3ee2e6f2-2ec3-11e4-82d0-6a36c984c329.png)

image: test.png
resolution: 0.0254
origin: [0.0, 0.0, 0.0]
occupied_thresh: 0.8
free_thresh: 0.2
negate: 1

**Comment by etsardou** [comment]
Hey there! The problem is that the specific image is layered and not RGB. You can use an image manipulation tool to change this (for example with Gimp you can go to Image->Mode->RGB) and then it will work. I attach the RGB image as well :)
![test_map](https://cloud.githubusercontent.com/assets/5663091/4077730/b819480c-2ec5-11e4-9404-876639b273f5.png)
